USE customer_behavior;

SELECT * FROM customer;

-- Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as revenue
from customer
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id
from customer
where discount_applied = 'Yes' and purchase_amount > (select avg(purchase_amount) from customer)
group by customer_id;

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating), 2) as Average_rating
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, round(avg(purchase_amount), 2)
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
select subscription_status, count(customer_id) as Total_customers,
round(avg(purchase_amount), 2) as Average_spend,
sum(purchase_amount) as Total_revenue
from customer
group by subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, round(avg(discount_applied = 'Yes')*100, 2) as Percentage_purchase
from customer
group by item_purchased
order by  Percentage_purchase desc
limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

with customer_type as (
select case
            when previous_purchases = 1 then 'New'
            when previous_purchases between 2 and 10 then 'Returning'
            else 'Loyal' end as customer_segment
from customer
)

select customer_segment, count(*) as 'Number of customer'
from customer_type
group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category?
with most_purchased as (
select category, item_purchased, count(*) as total_orders,
row_number() over (
partition by category
order by count(*) desc) as rn
from customer
group by category, item_purchased
)
select rn as item_rank, category, item_purchased, total_orders
from most_purchased
where rn<=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(*) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;

-- Q10. What is the revenue contribution of each age group?
select row_number() over(
order by sum(purchase_amount) desc) as item_rank,
age_group, sum(purchase_amount) as revenue_contribution
from customer
group by age_group
order by revenue_contribution desc;

